name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Application
      run: go build -o myapp

    - name: Copy to Server
      uses: appleboy/scp-action@v0.2.0
      with:
        host: 217.160.248.96
        username: root
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        source: myapp
        target: /root/voteapp-deploy

    - name: Restart Application on Server
      uses: appleboy/ssh-action@v0.5.0
      with:
        host: 217.160.248.96
        username: root
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          cd /root/voteapp-deploy
          ./myapp
