name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build and deploy
      run: |
        go build -o myapp
        scp myapp root@217.160.248.96:/root/voteapp-deploy
        ssh root@217.160.248.96 "cd /root/voteapp-deploy && ./myapp"

      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
