name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build and deploy
      run: |
        go build -o myapp
        scp myapp user@your-server-ip:/path/to/deployment/folder/
        ssh user@your-server-ip "cd /path/to/deployment/folder/ && ./myapp"

      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
