name: deploy infra, build app

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Add a step to copy the SSH public key file
      - name: Copy SSH public key
        run: |
          mkdir -p /tmp
          cp infrastructure/ssh-pub-key /tmp/ssh-pub-key

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7 # Specify the version you need

      - name: Set IonosCloud Token
        env:
          IONOS_TOKEN: ${{ secrets.TF_TOK }}
        run: |
          export IONOS_TOKEN

      - name: Deploy Infrastructure
        run: |
          cd infrastructure
          terraform init
          terraform apply -auto-approve
          # Save the server_ip output to a file
          terraform output -raw server_ip > /tmp/server_ip
        env:
          TF_VAR_other_variable: value
          IONOS_TOKEN: ${{ secrets.TF_TOK }}

      - name: Check IP File?
        run: |
          cat /tmp/server_ip 
          export SERVER_IP=$(cat /tmp/server_ip)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build and deploy
        uses: appleboy/ssh-action@master
        id: build
        with:
          host: ${{ env.SERVER_IP }} # Use the environment variable here instead of ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            echo "Building the application..."
            cd /root/go-vote-app-v2
            chmod +x run.sh
            go build -o myapp
            ./run.sh
