name: deploy and run webserver

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build and deploy
        uses: appleboy/ssh-action@master
        id: build
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            echo "Building the application..."
            cd /root/go-vote-app-v2
            go build -o myapp
            echo "Running the application on the server..."
            setsid ./myapp &  # Start the process in the background and detach it from the terminal
            echo $! > myapp.pid  # Save the PID to a file for later use
    
      
      - name: Finish and destroy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            sleep 20
            echo "Stopping the application on the server..."
            pkill -P $(cat myapp.pid)  # Kill the process group using the saved PID
            rm myapp.pid  # Clean up the PID file
            rm /root/go-vote-app-v2/myapp
            rm -rf /root/go-vote-app-v2/badger-db
