name: test actions pipeline

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run short script
      run: |
        echo Hello, world!!
        sleep 15
        echo Goodbye!