name: deploy and run webserver

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build and deploy
        uses: appleboy/ssh-action@master
        id: build
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            echo "Building the application..."
            cd /root/go-vote-app-v2
            go build -o myapp
            ./myapp &
            sleep 10
            echo "Stopping the application on the server..."
            pkill -f myapp 
            rm /root/go-vote-app-v2/myapp
            rm /root/go-vote-app-v2/myapp