name: test run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run short script
      run: |
        echo Hello, world!
        sleep 15
        echo Goodbye!

    - name: Run multi line script
      run: |
        echo "${{github.workspace}}"